config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  resources :contests
  devise_for :users, path: '/', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'new'
  }

  resources :problems
  post 'contests/:contest_id/register' => 'contests#register', :as => :register_contest

  root to: 'home_page#index'
end

app/models/contest.rb
class Contest < ApplicationRecord
  has_and_belongs_to_many :problems
  has_and_belongs_to_many :users

  validates :name, presence: true
  validates :start, presence: true
  validates :duration, presence: true

  def ended?
    # TODO:
    false
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]

  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
    @alph = ("A".."Z").to_a
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(contest_params)
    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def register
    @contest = Contest.find(params[:contest_id])
    @contest.users << current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:name, :start, :duration, problem_ids: [])
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= form_for(contest) do |f| %>
  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, autofocus: true, required: true, placeholder: 'Name', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :start, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.datetime_select :start, required: true, html_options: {class: 'form-control custom-select', type: 'datetime-local'} %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :duration, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.number_field :duration, required: true, placeholder: 'Duration (minutes)', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :problem_ids, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.select :problem_ids, Problem.pluck(:name, :id), {}, { multiple: true, class: 'form-control custom-select'} %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success'%>
  </div>
<% end %>

app/views/contests/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Editing Contest</h1>
    </div>

    <div class="col-md-12">
      <%= render 'form', contest: @contest %>
    </div>
  </div>
</div>

app/views/contests/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 push-md-3">
      <h1>Contests</h1>
    </div>

    <div class="row">
      <table class="table table-bordered table-hover table-responsive">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Start</th>
            <th>Duration</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @contests.each do |contest| %>
            <tr>
              <td><%= contest.id %></td>
              <td><%= link_to contest.name, contest_path(contest) %></td>
              <td><a target="_blank" href="https://www.timeanddate.com/worldclock/fixedtime.html?day=<%=contest.start.day%>&month=<%=contest.start.month%>&year=<%=contest.start.year%>&hour=<%=contest.start.hour%>&min=<%=contest.start.min%>&sec=<%=contest.start.sec%>"><%= contest.start %></a></td>
              <td><%= contest.duration %> min </td>
              <td>
                <% if user_signed_in? %>
                  <% if (contest.users.all.include?(current_user)) %>
                    REGISTERED
                  <% else %>  
                    <%= link_to 'register', register_contest_url(contest), method: :post, class: 'btn btn-xs btn-secondary' %>
                  <% end %>
                <% else %>
                  Log in to register!
                <% end %>
                <%= link_to 'Edit', edit_contest_path(contest), class: 'btn btn-xs btn-secondary' if(user_signed_in? and current_user.admin) %>
                <%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' if(user_signed_in? and current_user.admin) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to 'New Contest', new_contest_path, class: 'btn btn-primary' if(user_signed_in? and current_user.admin) %>

    </div>
  </div>
</div>

app/views/contests/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>New Contest</h1>
    </div>

    <div class="col-md-12">
      <%= render 'form', contest: @contest %>
    </div>
  </div>
</div>

app/views/contests/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="card">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs panel-tabs">
            <li class="nav-item">
              <a class="nav-link active" href="#problems" data-toggle="tab" role="tab">Problems</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#standings" data-toggle="tab" role="tab">Standings</a>
            </li>
          </ul>
        </div>
        <div class="card-block main-content">
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="problems">
              <div class="row">
                <table class="table table-striped table-bordered table-hover table-responsive contest">
                  <thead>
                    <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Time Limit</th>
                    <th>Memory Limit</th>
                    <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                  <% @contest.problems.each_with_index do |problem, i| %>
                    <tr>
                      <td><%= @alph[i] %></td>
                      <td><%= link_to problem.name, problem_path(problem) %></td>
                      <td><%= problem.time_limit %>s</td>
                      <td><%= problem.memory_limit %>mb</td>
                      <td>Not Tried</td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
            <div role="tabpanel" class="tab-pane fade" id="standings">
              <div class="row">
                <table class="table table-striped table-bordered table-hover table-responsive contest">
                  <thead>
                    <tr>
                    <th>Team</th>
                    <th>Total</th>
                    <th>Penalty</th>
                    <% @contest.problems.each_with_index do |problem, i| %>
                      <th><%= @alph[i] %></th>
                    <% end %>
                    </tr>
                  </thead>
                  <tbody>
                    <% @scoreboard_users = [] %>
                    <% @contest.users.each do |user| %>
                      <% @verdicts = [] %>
                      <% @score = 0 %>
                      <% @penalty = 0 %>
                      <% @contest.problems.each do |problem| %>
                        <% @verdict = user.get_verdict(problem, @contest.start, @contest.start + (@contest.duration*60)) %>
                        <% @verdicts << @verdict[0] %>
                        <% @score += 1 if @verdict[0] >= 1 %>
                        <% print @verdict[1] %>
                        <% @penalty += (@verdict[0]-1)*20 + Integer(@verdict[1] - @contest.start)/60 if @verdict[0] >= 1 %>
                      <% end %>
                      <% @current_user = [user.name, @score, @penalty] %>
                      <% @contest.problems.each_with_index do |problem, i| %>
                        <% @current_user << @verdicts[i] %>
                      <% end %>
                      <% @scoreboard_users.push(@current_user) %>
                    <% end %>
                    <% @scoreboard_users.sort_by{|c| [-c[1], c[2]]}.each do |user| %>
                    <tr>
                      <% user.each_with_index do |d, i| %>
                        <% if(i>2) %>
                          <td class="baloon">
                        <% else %>
                          <td>
                        <% end %>
                          <%=d%>
                        </td>
                      <% end %>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>  
          </div>  
        </div>
        <div class="card-block">
          <%= link_to 'Edit', edit_contest_path(@contest), class: 'btn btn-success text-white' if(user_signed_in? and current_user.admin) %>
          <%= link_to 'Back', contests_path, class: 'btn btn-success text-white' if(user_signed_in? and current_user.admin) %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card">
        <div class="card-header">
          <%= @contest.name %>
        </div>
        <div class="card-block">
          <p>Start: <%= @contest.start %></p>
          <p>Duration: <%= @contest.duration %><%=" "%>minutes</p>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          Statistics
        </div>
        <div class="card-block">
          <p>A: 1/2</p>
          <p>B: 0/1</p>
          <p>C: 1/1</p>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          Announcements
        </div>
        <div class="card-block">
          <p>Announcements fake 1</p>
          <p>Announcements fake 2</p>
        </div>
      </div>
    </div>
  </div>
</div>