config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  resources :contests
  devise_for :users, path: '/', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'new'
  }

  resources :problems
  post 'contests/:contest_id/register' => 'contests#register', :as => :register_contest

  root to: 'home_page#index'
end

app/models/problem.rb
class Problem < ApplicationRecord
  has_many :test_cases
  has_many :submissions
  has_and_belongs_to_many :contests

  validates :name, presence: true
  validates :description, presence: true
  validates :input_description, presence: true
  validates :output_description, presence: true
  validates :time_limit, presence: true
  validates :memory_limit, presence: true

  def is_ready?
    # A problem is only ready when it has at least one test case.
    return !self.test_cases.blank?
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
  end

  # GET /problems/new
  def new
    @problem = Problem.new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(problem_params)
    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render :show, status: :created, location: @problem }
      else
        format.html {
          flash.now[:alert] = @problem.errors.full_messages.join(', ')
          render :new
        }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem.destroy
    respond_to do |format|
      format.html { redirect_to problems_url, notice: 'Problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:name, :description, :input_description,
                                      :output_description, :note, :time_limit,
                                      :memory_limit)
    end
end

app/views/problems/_form.html.erb
<%= form_for(problem) do |f| %>
  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, autofocus: true, required: true, placeholder: 'Name', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :description, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.text_area :description, rows: 10, required: true, placeholder: 'Description', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label "Input", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-6">
      <%= f.text_area :input_description, rows: 3, required: true, placeholder: 'Sample input', class: 'form-control' %>
    </div>
    <div class="col-sm-4">
      <%= f.label "Input package" %>
      <%= f.file_field :input_description %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label "Output", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-6">
      <%= f.text_area :output_description, rows: 3, required: true, placeholder: 'Sample output', class: 'form-control' %>
    </div>
    <div class="col-sm-4">
      <%= f.label "Output package" %>
      <%= f.file_field :output_description %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :time_limit, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.number_field :time_limit, required: true, placeholder: 'Time Limit (seconds)', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :memory_limit, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.number_field :memory_limit, required: true, placeholder: 'Memory Limit (kb)', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :note, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.text_field :note, placeholder: 'Note', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label "Custom check", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.text_area :custom_check, rows: 3, placeholder: 'Custom check', class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Create', class: 'btn btn-success'%>
  </div>
<% end %>

app/views/problems/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Editing Problem</h1>
    </div>

    <div class="col-md-12">
      <%= render 'form', problem: @problem %>
    </div>
  </div>
</div>

app/views/problems/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 push-md-3">
      <h1>Problems</h1>
    </div>

    <div class="col-md-12">
      <table class="table table-striped table-bordered table-hover table-responsive contest">
        <thead>
          <tr>
          <th>Name</th>
          <th>Time Limit</th>
          <th>Memory Limit</th>
          <th colspan=2></th>
          </tr>
        </thead>

        <tbody>
          <% @problems.each do |problem| %>
            <tr>
              <td><%= link_to problem.name, problem_path(problem) %></td>
              <td><%= problem.time_limit %>s</td>
              <td><%= problem.memory_limit %>mb</td>
              <td>
                <%= link_to 'Edit', edit_problem_path(problem), class: 'btn btn-xs btn-secondary' if(user_signed_in? and current_user.admin) %>
                <%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' if(user_signed_in? and current_user.admin) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to 'New Problem', new_problem_path, class: 'btn btn-primary' if(user_signed_in? and current_user.admin)%>

    </div>
  </div>
</div>

app/views/problems/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Create new Problem</h1>
    </div>

    <div class="col-md-12">
      <%= render 'form', problem: @problem %>
    </div>
  </div>
</div>

app/views/problems/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="card">
        <div class="card-block">
          <h2 class="card-title"><%= @problem.name %></h2>

          <div class="card">
            <div class="card-block">
              <%= @problem.description.html_safe %>
            </div>
          </div>

          <div class="card">
            <div class="card-block">
              <h4>Input:</h4>
              <%= @problem.input_description.html_safe %>
            </div>
            <div class="card-block">
              <h4>Output:</h4>
              <%= @problem.output_description.html_safe %>
            </div>
          </div>
          <%if(not @problem.note.blank?)%>
          <div class="card">
            <div class="card-block">
              <h4>Note:</h4>
              <%= @problem.note %>
            </div>
          </div>
          <% end %>
        </div>

        <div class="card-block">
          <%= link_to 'Edit', edit_problem_path(@problem), class: 'card-link btn btn-primary' if(user_signed_in? and current_user.admin) %>
          <%= link_to 'Back', problems_path, class: 'card-link btn btn-primary' if(user_signed_in? and current_user.admin) %>
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">Contest 2</h4>
          <p>Runing: 57 minutes left</p>
        </div>
        <div class="card-action">
          <a class="btn" href="#">Standings</a>
          <%= link_to '<i class="fa fa-paper-plane" aria-hidden="true"></i> Submit'.html_safe, new_submission_url, class: 'card-link btn btn-success'%>
        </div>
      </div>

      <div class="card">
        <div class="card-block">
          <h4 class="card-title">My Submissions</h4>
        <div class="card-action">
          Submission 2 | WA
        </div>
        <div class="card-action">
          Submission 1 | TLE
        </div>
        </div>
      </div>
    </div>
  </div>
</div>