config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  resources :contests
  devise_for :users, path: '/', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'new'
  }

  resources :problems
  post 'contests/:contest_id/register' => 'contests#register', :as => :register_contest

  root to: 'home_page#index'
end

app/views/shared/_flashes.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar fixed-navbar navbar-toggleable-md navbar-light bg-faded">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to '@BROnlineJudge', 'https://github.com/BROnlineJudge', class: 'nav-link' %></li>
    </ul>
  </nav>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded navtop">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to '[BROJ]', root_path, class: "navbar-brand" %>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to "PROBLEMS", problems_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "CONTESTS", contests_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "SUBMISSIONS", submissions_path, class: "nav-link" %></li>

      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to "Log out", destroy_user_session_url, method: :delete, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to 'Log in', new_user_session_url, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>