config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  resources :contests
  devise_for :users, path: '/', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'new'
  }

  resources :problems
  post 'contests/:contest_id/register' => 'contests#register', :as => :register_contest

  root to: 'home_page#index'
end

app/models/submission.rb
class Submission < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :problem
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /submissions
  # GET /submissions.json
  def index
    if user_signed_in?
      @submissions = Submission.all.select{|s| s.user_id == current_user.id}
      @submissions = @submissions.sort_by{|c| c.created_at}.reverse()
    else
      redirect_to new_user_session_url, notice: 'Login required.'
    end
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # POST /submissions
  # POST /submissions.json
  def create
    params = submission_params
    params["user_id"] = current_user.id
    @submission = Submission.new(params)
    @submission.verdict = "Not Yet Judged"
    respond_to do |format|
      if @submission.save
        format.html { redirect_to submissions_url, notice: 'Submission was successfully created.' }
        filename = "solutions/" + @submission.id.to_s
        File.open(filename,  "w") { |file| file.write(@submission.code) }
        system "./submit.sh " + filename + " " + @submission.language + " \'" + 
               Problem.find_by(id: @submission.problem_id).name + "\'" + " " +  
               "http://localhost:1234/submissions/" + @submission.id.to_s + " ;"
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to submissions_url, notice: 'Submission was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:verdict, :language, :execution_time, 
                                         :code, :problem_id, :user_id)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_for(submission) do |f| %>

  <div class="form-group row">
    <%= f.label :language, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.select :language, [["c", "c"], ["cpp", "cpp"], ["python", "py"],
      ["java", "java"]], {required: true,}, { class: 'form-control custom-select'} %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :code, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.text_area :code, rows: 10, required: true, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :problem, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.select :problem_id, Problem.pluck(:name, :id), {}, { class: 'form-control custom-select'} %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-success'%>
  </div>
<% end %>

app/views/submissions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 push-md-3">
      <h1>Submissions</h1>
    </div>

    <div class="col-md-12">
      <table class="table table-striped table-bordered table-hover table-responsive contest">
        <thead>
          <tr>
          <th>Problem</th>
          <th>Verdict</th>
          <th>Language</th>
          </tr>
        </thead>

        <tbody>
          <% @submissions.each do |submission| %>
            <tr>
              <td><%= Problem.find_by(id: submission.problem_id).name %></td>
              <td><%= link_to submission.verdict, submission_path(submission) %></td>
              <td><%= submission.language %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to 'New Submission', new_submission_path, class: 'btn btn-primary' %>

    </div>
  </div>
</div>

app/views/submissions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>New Submission</h1>
    </div>

    <div class="col-md-12">
      <%= render 'form', submission: @submission %>
    </div>
  </div>
</div>